### ISSUE TITLE
Add more boilerplate

### ISSUE THREAD

**Issue by svx** [testthedocs/cookiecutter-plone-training#1]
- for tests
- add prefix to index and glossary
- git hooks ?
- gitignore with _build and such

**Comment by pbauer** [comment]
add js, css and html for the use of:

```
..  admonition:: Solution
    :class: toggle
```

**Comment by svx** [comment]
@pbauer As far as I can see that is already done, at least there is already the whole _static dir.

I cannot find more on the training repo itself. Feel free to reopen if there is still something missing :)
